const Discord = require('discord.js');
const client = new Discord.Client();
const token = 'NzUwMDQxMTE5NTk3MDAyODgy.X00wOg.CetlmrM4jL12GoKknM1BCCElLOI'

client.on("ready", () => {
    client.user.setActivity('Advertising Core', { type: 'WATCHING' })
    console.log('On the discord internets')
});



client.on('message', msg => {
  if (msg.content.includes('discord.gg')) {
      msg.channel.send({embed:
        {
          "title": "**__REMINDER__**",
          "description": ":white_check_mark: **All your posts will be automatically __deleted__ if you leave this server** \n :ballot_box_with_check: **Make sure to read the <#722811237339234334> before posting anywhere in the server! **\n :white_check_mark: **Take a look at <#749958927369764906> to get better advertising!**",
          "color": 16711680,
          "footer": {
            "text": "This Was Auto Generated By AC Manager. If any bugs, DM Soceresy#0001"
}}})}});

//kick

client.on('message', message => {
 
    if (!message.guild) return;
   
   
    if (message.content.startsWith('ac!kick')) { //**This is the command.**\\
     
      const user = message.mentions.users.first(); // This says if you mention this user, it is talking about that user
     
      if (user) {
     
        const member = message.guild.member(user);
     
        if (member) {
       
          member.kick('Optional reason that will display in the audit logs').then(() => {
         
            message.reply(`Successfully kicked ${user.tag}, you should feel bad! They will never be able to rejoin until they click join again!`);
          }).catch(err => {
           
            message.reply('I was unable to kick the member. Check if their roles are higher then mine or if they have administrative permissions!');
           
            console.error(err);
          });
        } else {
         
          message.reply('That user isn\'t in this guild!');
        }
   
      } else {
        message.reply('You didn\'t mention the user to kick!'); // Thus is creating a message so that you know if you failed
  // The / is to show the script that the (') is not the end of it
      }
    }
});

//ban
client.on('message', message => {
 
    if (!message.guild) return;
   
   
    if (message.content.startsWith('ac!ban')) { //**This is the command.**\\
     
      const user = message.mentions.users.first(); // This says if you mention this user, it is talking about that user
     
      if (user) {
     
        const member = message.guild.member(user);
     
        if (member) {
       
          member.ban('Optional reason that will display in the audit logs').then(() => {
         
            message.reply(`Successfully banned ${user.tag}, you should feel bad! They will never be able to rejoin until they click join again!`);
          }).catch(err => {
           
            message.reply('I was unable to ban the member. Check if their roles are higher then mine or if they have administrative permissions!');
           
            console.error(err);
          });
        } else {
         
          message.reply('That user isn\'t in this guild!');
        }
   
      } else {
        message.reply('You didn\'t mention the user to ban!'); // Thus is creating a message so that you know if you failed
  // The / is to show the script that the (') is not the end of it
      }
    }
});


client.on('message', msg => {
    if (msg.content === 'ac!help') {
        msg.channel.send({embed: {
            color: 2237479,
            author: {
              name: client.user.username,
              icon_url: client.user.avatarURL
            },
            title: "Commands!",
            description: "This Is All The Commands For The Bot!",
            fields: [{
                name: "ac!kick",
                value: "Kicks A Member! Must Be A Role That Can Kick"
              },
              {
                name: "ac!ban",
                value: "Bans A Member! Must Be A Role That Can Ban!"
              },
            ],
            
            footer: {
              icon_url: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fdiscordemoji.com%2Fassets%2Femoji%2F3942_DiscordStaff.png&f=1&nofb=1 ',
              text: "Made With Love! -Soceresy#0001 (DMs Open For Bot Requests)"
            }
          }
        });
    }
});



client.login(token);